sudo: required
services : 
  - docker

scripts :
  - docker build -t mubeen636/node .
  - docker images mubeen636/node

before-deploy : 
  -docker login -u mubeen636 -p d3ng3y@6036

deploy : 
  provider : script
  script : docker push mubeen636/node
  on:
    branch : master